baseURL = 'https://annisatahira.github.io/contoh/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-fresh'

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
